I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 227, in script
    show dog normal at right with fadein
  File "game/script.rpy", line 227, in <module>
    show dog normal at right with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 227, in script
    show dog normal at right with fadein
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 1271, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\python.py", line 1725, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\python.py", line 1719, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 227, in <module>
    show dog normal at right with fadein
NameError: name 'fadein' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
waves '87: Business Cruizin' 1.0
